### ISSUE TITLE
about AIMED-RL

### ISSUE THREAD

**Issue by zhang-x-h** [zRapha/AIMED#5]
when I use optional=AIMED-RL   load file gradient_boosting.pkl to predict score,  it will occur "AttributeError: 'numpy.ndarray' object has no attribute 'predict_proba'", do I need to modify something? the file gradient_boosting.pkl type is numpy.ndarray

**Comment by SebieF** [comment]
Hello,

thank you for your interest in AIMED-RL and sorry for the delayed response. Unfortunately, there have been some compatibility problems between AIMED-RL and the other papers, such as AIMED and ARMED. Hence, please refer to by [fork](https://github.com/SebieF/AIMED) of this repository, where you can find a working version of AIMED-RL with fixed requirements. The error you referred is caused by a wrong version of scikit-learn (amongst others). You can also find a more exhaustive description of how-to use AIMED-RL in this [blog article](https://sebief.github.io/it-security/tutorial/aimedRL/). 
If you face any more issues, please let us know!
